package com.posthog.android

import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFile
import org.gradle.api.provider.Provider
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.TaskProvider
import java.io.File
import java.util.Properties

@CacheableTask
abstract class InjectPostHogMetaPropertiesIntoAssetsTask : DefaultTask() {
    @get:PathSensitive(PathSensitivity.RELATIVE)
    @get:InputFiles
    abstract val inputDir: DirectoryProperty

    @get:OutputDirectory
    val outputDir: DirectoryProperty = project.objects.directoryProperty()
        get() {
            // AGP < 8.3 sets an output folder which contains the input folder
            // input:  app/intermediates/assets/release/mergeReleaseAssets
            // output: app/intermediates/assets/release/
            // re-route output to a sub directory instead,
            // as otherwise this breaks the gradle cache functionality

            @Suppress("SENSELESS_COMPARISON")
            if (field == null || !field.isPresent) {
                return field
            }

            if (!field.get().asFile.name.equals(name)) {
                field.set(File(field.get().asFile, name))
            }

            return field
        }

    // we only care about file contents
    @get:PathSensitive(PathSensitivity.NONE)
    @get:InputFiles
    abstract val inputPropertyFiles: ConfigurableFileCollection

    @TaskAction
    fun taskAction() {
        val input = inputDir.get().asFile
        val output = outputDir.getAndDelete()
        output.mkdirs()

        input.copyRecursively(output, overwrite = true)

        // merge props
        val props = Properties()
        inputPropertyFiles.forEach { inputFile ->
            loadPropertiesMaybe(inputFile)?.let { props.putAll(it) }
        }

        // write props
        val propsFile = File(output, POSTHOG_DEBUG_META_PROPERTIES_OUTPUT)
        propsFile.writer().use { props.store(it, "Generated by com.posthog.android") }
    }

    companion object {
        internal const val POSTHOG_DEBUG_META_PROPERTIES_OUTPUT = "posthog-meta.properties"

        fun register(
            project: Project,
            tasksGeneratingProperties: List<TaskProvider<out PropertiesFileOutputTask>>,
            taskSuffix: String = "",
        ): TaskProvider<InjectPostHogMetaPropertiesIntoAssetsTask> {
            val inputFiles: List<Provider<RegularFile>> =
                tasksGeneratingProperties.map { it.flatMap { task -> task.outputFile } }
            return project.tasks.register(
                "injectPostHogMetaPropertiesIntoAssets$taskSuffix",
                InjectPostHogMetaPropertiesIntoAssetsTask::class.java,
            ) {
                inputPropertyFiles.setFrom(inputFiles)
            }
        }
    }
}
