// Portions of this file are derived from getsentry/sentry-android-gradle-plugin
// Copyright (c) 2020 Sentry
// Licensed under the MIT License: https://github.com/getsentry/sentry-android-gradle-plugin/blob/main/LICENSE

package com.posthog.android

import com.posthog.android.PostHogGenerateMapIdTask.Companion.POSTHOG_PROGUARD_MAPPING_MAP_ID_PROPERTY
import org.apache.tools.ant.taskdefs.condition.Os
import org.gradle.api.Task
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.logging.Logger
import org.gradle.api.tasks.TaskProvider
import java.io.File
import java.security.DigestInputStream
import java.security.MessageDigest
import java.util.Locale
import java.util.Properties

internal fun ByteArray.toHex(): String {
    val result = CharArray(size * 2) { ' ' }
    var i = 0
    forEach {
        val n = it.toInt()
        result[i++] = Character.forDigit(n shr 4 and 0xF, 16)
        result[i++] = Character.forDigit(n and 0xF, 16)
    }
    return String(result)
}

/** Returns md5/sha256 hash of the file contents */
internal fun File.contentHash(): String {
    // first try to read hash generated by R8, which is located in the first 20 lines of mapping
    // lines are lazily iterated over, so even on huge files performance should not be a problem
    var hash: String? = null
    var index = 0
    bufferedReader().lines().use { lines ->
        for (line in lines) {
            hash = line.substringAfter("# pg_map_hash: SHA-256 ", missingDelimiterValue = "")
            if (++index > 20 || !hash.isNullOrBlank()) {
                break
            }
        }
    }
    if (!hash.isNullOrBlank()) {
        return hash!!
    }

    // otherwise fall back to calculating hash ourselves
    val md = MessageDigest.getInstance("MD5")
    DigestInputStream(inputStream(), md).buffered().readAllBytes()
    return md.digest().toHex()
}

internal fun String.capitalizeUS() =
    if (isEmpty()) {
        ""
    } else {
        substring(0, 1).uppercase(Locale.US) + substring(1)
    }

internal fun loadProperties(file: File): Properties {
    check(file.exists()) { "${file.name} properties file is missing" }

    return Properties().also { properties -> file.inputStream().use { properties.load(it) } }
}

internal fun loadPropertiesMaybe(file: File): Properties? {
    if (!file.exists()) {
        return null
    }

    return loadProperties(file)
}

internal fun readMapIdFromFile(file: File): String {
    val props = loadProperties(file)
    val uuid = props.getProperty(POSTHOG_PROGUARD_MAPPING_MAP_ID_PROPERTY)
    check(uuid != null) { "$POSTHOG_PROGUARD_MAPPING_MAP_ID_PROPERTY property is missing" }
    return uuid
}

internal fun withLogging(
    logger: Logger,
    varName: String,
    initializer: () -> TaskProvider<Task>?,
) = initializer().also { logger.info("$varName is ${it?.name}") }

internal fun DirectoryProperty.getAndDelete(): File {
    val file = get().asFile
    if (file.isDirectory) {
        file.deleteRecursively()
    } else {
        file.delete()
    }
    return file
}

internal const val POSTHOG_CLI_DEFAULT_EXECUTABLE = "posthog-cli"

/**
 * Locates posthog-cli for builds whose environment lacks the shell PATH —
 * IDE-launched Gradle daemons don't source shell profiles, so a CLI installed
 * via nvm/npm is invisible to a plain PATH lookup. Mirrors the lookup order of
 * posthog-ios build-tools/upload-symbols.sh: an explicitly configured
 * executable is used verbatim, a PATH hit keeps the plain name, then
 * well-known install locations are probed.
 */
internal fun resolvePostHogCliExecutable(
    configured: String,
    logger: Logger,
    environment: Map<String, String> = System.getenv(),
    home: File = File(System.getProperty("user.home")),
): String {
    if (configured != POSTHOG_CLI_DEFAULT_EXECUTABLE || Os.isFamily(Os.FAMILY_WINDOWS)) {
        return configured
    }

    val onPath =
        environment["PATH"]
            ?.split(File.pathSeparator)
            ?.any { File(it, configured).isExecutableFile() } ?: false
    if (onPath) {
        return configured
    }

    val candidates =
        buildList {
            add(File(home, ".posthog/posthog-cli"))
            addAll(nodeVersionBins(File(home, ".nvm/versions/node")))
            File("/opt/homebrew/Cellar/nvm").listFilesSafe().forEach { cellar ->
                addAll(nodeVersionBins(File(cellar, "versions/node")))
            }
            add(File("/usr/local/bin/posthog-cli"))
            add(File("/opt/homebrew/bin/posthog-cli"))
            add(File(home, ".cargo/bin/posthog-cli"))
            add(File(home, ".local/bin/posthog-cli"))
        }

    val found = candidates.firstOrNull { it.isExecutableFile() }
    if (found != null) {
        logger.info("posthog-cli not on PATH, using ${found.absolutePath}")
        return found.absolutePath
    }
    logger.warn(
        "posthog-cli not found on PATH or in known install locations; " +
            "install it (npm install -g @posthog/cli) or set postHogExecutable on the task.",
    )
    return configured
}

private fun File.isExecutableFile(): Boolean = isFile && canExecute()

private fun File.listFilesSafe(): List<File> = listFiles()?.toList() ?: emptyList()

/** `<root>/vX.Y.Z/bin/posthog-cli` candidates, newest node version first. */
private fun nodeVersionBins(root: File): List<File> =
    root.listFilesSafe()
        .sortedWith(NODE_VERSION_DIR_ORDER.reversed())
        .map { File(it, "bin/posthog-cli") }

private val NODE_VERSION_DIR_ORDER =
    Comparator<File> { a, b ->
        val x = versionKey(a.name)
        val y = versionKey(b.name)
        for (i in 0 until maxOf(x.size, y.size)) {
            val cmp = x.getOrElse(i) { 0L }.compareTo(y.getOrElse(i) { 0L })
            if (cmp != 0) return@Comparator cmp
        }
        0
    }

private fun versionKey(name: String): List<Long> = Regex("\\d+").findAll(name).mapNotNull { it.value.toLongOrNull() }.toList()
