// Portions of this file are derived from getsentry/sentry-android-gradle-plugin
// Copyright (c) 2020 Sentry
// Licensed under the MIT License: https://github.com/getsentry/sentry-android-gradle-plugin/blob/main/LICENSE

package com.posthog.android

import com.posthog.android.PostHogGenerateMapIdTask.Companion.POSTHOG_PROGUARD_MAPPING_MAP_ID_PROPERTY
import org.apache.tools.ant.taskdefs.condition.Os
import org.gradle.api.Project
import org.gradle.api.Task
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.logging.Logger
import org.gradle.api.tasks.TaskProvider
import java.io.File
import java.security.DigestInputStream
import java.security.MessageDigest
import java.util.Locale
import java.util.Properties

internal fun ByteArray.toHex(): String {
    val result = CharArray(size * 2) { ' ' }
    var i = 0
    forEach {
        val n = it.toInt()
        result[i++] = Character.forDigit(n shr 4 and 0xF, 16)
        result[i++] = Character.forDigit(n and 0xF, 16)
    }
    return String(result)
}

/** Returns md5/sha256 hash of the file contents */
internal fun File.contentHash(): String {
    // first try to read hash generated by R8, which is located in the first 20 lines of mapping
    // lines are lazily iterated over, so even on huge files performance should not be a problem
    var hash: String? = null
    var index = 0
    bufferedReader().lines().use { lines ->
        for (line in lines) {
            hash = line.substringAfter("# pg_map_hash: SHA-256 ", missingDelimiterValue = "")
            if (++index > 20 || !hash.isNullOrBlank()) {
                break
            }
        }
    }
    if (!hash.isNullOrBlank()) {
        return hash!!
    }

    // otherwise fall back to calculating hash ourselves
    val md = MessageDigest.getInstance("MD5")
    DigestInputStream(inputStream(), md).buffered().readAllBytes()
    return md.digest().toHex()
}

internal fun String.capitalizeUS() =
    if (isEmpty()) {
        ""
    } else {
        substring(0, 1).uppercase(Locale.US) + substring(1)
    }

internal fun loadProperties(file: File): Properties {
    check(file.exists()) { "${file.name} properties file is missing" }

    return Properties().also { properties -> file.inputStream().use { properties.load(it) } }
}

internal fun loadPropertiesMaybe(file: File): Properties? {
    if (!file.exists()) {
        return null
    }

    return loadProperties(file)
}

internal fun readMapIdFromFile(file: File): String {
    val props = loadProperties(file)
    val uuid = props.getProperty(POSTHOG_PROGUARD_MAPPING_MAP_ID_PROPERTY)
    check(uuid != null) { "$POSTHOG_PROGUARD_MAPPING_MAP_ID_PROPERTY property is missing" }
    return uuid
}

internal fun withLogging(
    logger: Logger,
    varName: String,
    initializer: () -> TaskProvider<Task>?,
) = initializer().also { logger.info("$varName is ${it?.name}") }

internal fun DirectoryProperty.getAndDelete(): File {
    val file = get().asFile
    if (file.isDirectory) {
        file.deleteRecursively()
    } else {
        file.delete()
    }
    return file
}

internal const val POSTHOG_CLI_DEFAULT_EXECUTABLE = "posthog-cli"

internal const val POSTHOG_DOTENV_FILE_PROPERTY = "posthog.dotenvFile"

/**
 * Value of the posthog.dotenvFile gradle property as an absolute path, or null
 * when unset/blank. Relative values resolve against the root project so a
 * single gradle.properties entry works from any module. The path reaches
 * posthog-cli (>= 0.8.4) as POSTHOG_CLI_DOTENV_FILE — process env still wins
 * inside the CLI, and a missing file is a warning there, not a failure.
 */
internal fun resolvePostHogDotenvFile(project: Project): String? {
    val value = project.findProperty(POSTHOG_DOTENV_FILE_PROPERTY)?.toString()?.trim()
    if (value.isNullOrEmpty()) {
        return null
    }
    val file = File(value)
    return if (file.isAbsolute) file.path else File(project.rootDir, value).path
}

internal const val POSTHOG_RELEASE_MODE_PROPERTY = "posthog.releaseMode"

internal const val POSTHOG_RELEASE_MODE_ENV = "POSTHOG_RELEASE_MODE"

/** How the release a build belongs to gets associated with the exceptions it reports. */
internal enum class PostHogReleaseMode(val cliValue: String) {
    /**
     * posthog-cli stamps the release onto the uploaded mapping file, and exceptions inherit it
     * from the mapping their frames resolved against. The behavior before event mode existed.
     */
    SYMBOL_SET("symbol-set"),

    /**
     * The mapping is uploaded release-independent, and each event resolves its own release from
     * the `$app_namespace` / `$app_version` / `$app_build` the SDK already sends. Nothing is
     * injected into the app. A map id is derived from the mapping's content, so two releases
     * sharing a mapping would otherwise both report whichever release uploaded it first.
     */
    EVENT("event"),
    ;

    internal companion object {
        fun from(value: String): PostHogReleaseMode? = values().firstOrNull { it.cliValue == value }
    }
}

/**
 * Release mode for this build: the `posthog.releaseMode` gradle property, then the
 * `POSTHOG_RELEASE_MODE` environment variable posthog-cli and the bundler plugins already read,
 * then [PostHogReleaseMode.SYMBOL_SET].
 *
 * An unrecognized value fails the build rather than falling back, so a typo can't silently leave
 * a build binding its mapping to a release it meant to keep independent.
 */
internal fun resolvePostHogReleaseMode(
    project: Project,
    environment: Map<String, String> = System.getenv(),
): PostHogReleaseMode {
    val value =
        project.findProperty(POSTHOG_RELEASE_MODE_PROPERTY)?.toString()?.trim()?.takeIf { it.isNotEmpty() }
            ?: environment[POSTHOG_RELEASE_MODE_ENV]?.trim()?.takeIf { it.isNotEmpty() }
            ?: return PostHogReleaseMode.SYMBOL_SET

    return PostHogReleaseMode.from(value)
        ?: error(
            "$POSTHOG_RELEASE_MODE_PROPERTY must be one of " +
                "${PostHogReleaseMode.values().joinToString { it.cliValue }}, was '$value'",
        )
}

/**
 * Locates posthog-cli for builds whose environment lacks the shell PATH —
 * IDE-launched Gradle daemons don't source shell profiles, so a CLI installed
 * via nvm/npm is invisible to a plain PATH lookup. An explicitly configured
 * executable is used verbatim. The existing PATH and global install lookup keeps
 * its precedence, with project-local npm launchers added as the final fallback.
 *
 * [workingDirectory] is the Android Gradle root. Its parent is checked as well
 * because React Native projects normally keep node_modules beside android/.
 */
internal fun resolvePostHogCliExecutable(
    configured: String,
    logger: Logger,
    environment: Map<String, String> = System.getenv(),
    home: File = File(System.getProperty("user.home")),
    workingDirectory: File? = null,
    isWindows: Boolean = Os.isFamily(Os.FAMILY_WINDOWS),
    cliInstallLocations: List<File>? = null,
    nodeInstallLocations: List<File>? = null,
): String {
    if (configured != POSTHOG_CLI_DEFAULT_EXECUTABLE || isWindows) {
        return configured
    }

    val launcherName = configured

    // Resolve a PATH hit to an absolute path instead of keeping the bare name:
    // a bare name is resolved against the daemon process's own environment,
    // which can differ from the build environment (IDE-launched daemons).
    val onPathDir =
        environment["PATH"]
            ?.split(File.pathSeparator)
            ?.firstOrNull { File(it, launcherName).isRunnableFile(isWindows) }
    if (onPathDir != null) {
        return File(onPathDir, launcherName).absolutePath
    }

    if (!isWindows) {
        val candidates =
            cliInstallLocations ?: buildList {
                add(File(home, ".posthog/posthog-cli"))
                addAll(nodeVersionBins(File(home, ".nvm/versions/node")))
                File("/opt/homebrew/Cellar/nvm").listFilesSafe().forEach { cellar ->
                    addAll(nodeVersionBins(File(cellar, "versions/node")))
                }
                add(File("/usr/local/bin/posthog-cli"))
                add(File("/opt/homebrew/bin/posthog-cli"))
                add(File(home, ".cargo/bin/posthog-cli"))
                add(File(home, ".local/bin/posthog-cli"))
            }

        val found = candidates.firstOrNull { it.isRunnableFile(isWindows = false) }
        if (found != null) {
            logger.info("posthog-cli not on PATH, using ${found.absolutePath}")
            return found.absolutePath
        }
    }

    val localLauncher =
        listOfNotNull(workingDirectory, workingDirectory?.parentFile)
            .distinct()
            .map { File(it, "node_modules/.bin/$launcherName") }
            .firstOrNull { it.isRunnableFile(isWindows) }
    val nodeExecutable = resolveNodeExecutable(environment, home, isWindows, nodeInstallLocations)
    if (localLauncher != null && nodeExecutable != null) {
        logger.info("using project-local posthog-cli at ${localLauncher.absolutePath}")
        return localLauncher.absolutePath
    }

    logger.warn(
        "posthog-cli not found in the project, on PATH, or in known install locations; " +
            "install it (npm install --save-dev @posthog/cli or npm install -g @posthog/cli) " +
            "or set postHogExecutable on the task.",
    )
    return configured
}

internal fun resolveNodeExecutable(
    environment: Map<String, String> = System.getenv(),
    home: File = File(System.getProperty("user.home")),
    isWindows: Boolean = Os.isFamily(Os.FAMILY_WINDOWS),
    knownInstallLocations: List<File>? = null,
): String? {
    val executableName = if (isWindows) "node.exe" else "node"
    val onPath =
        pathValue(environment)
            ?.split(File.pathSeparator)
            ?.map { File(it, executableName) }
            ?.firstOrNull { it.isRunnableFile(isWindows) }
    if (onPath != null) {
        return onPath.absolutePath
    }
    if (isWindows) {
        return null
    }

    val candidates =
        knownInstallLocations ?: buildList {
            addAll(nodeVersionExecutables(File(home, ".nvm/versions/node"), executableName))
            File("/opt/homebrew/Cellar/nvm").listFilesSafe().forEach { cellar ->
                addAll(nodeVersionExecutables(File(cellar, "versions/node"), executableName))
            }
            add(File("/usr/local/bin/node"))
            add(File("/opt/homebrew/bin/node"))
            add(File(home, ".local/bin/node"))
        }
    return candidates.firstOrNull { it.isRunnableFile(isWindows = false) }?.absolutePath
}

internal fun prependExecutableDirectoriesToPath(
    executables: List<String>,
    environment: Map<String, String>,
): Pair<String, String> {
    val pathKey = environment.keys.firstOrNull { it.equals("PATH", ignoreCase = true) } ?: "PATH"
    val path = environment[pathKey].orEmpty()
    val binDirectories = executables.mapNotNull { File(it).parent }.distinct()
    val entries = if (path.isEmpty()) binDirectories else binDirectories + path
    return pathKey to entries.joinToString(File.pathSeparator)
}

private fun pathValue(environment: Map<String, String>): String? =
    environment.entries.firstOrNull { it.key.equals("PATH", ignoreCase = true) }?.value

private fun File.isRunnableFile(isWindows: Boolean): Boolean = isFile && (isWindows || canExecute())

private fun File.listFilesSafe(): List<File> = listFiles()?.toList() ?: emptyList()

/** `<root>/vX.Y.Z/bin/posthog-cli` candidates, newest node version first. */
private fun nodeVersionBins(root: File): List<File> = nodeVersionExecutables(root, "posthog-cli")

private fun nodeVersionExecutables(
    root: File,
    executableName: String,
): List<File> =
    root.listFilesSafe()
        .sortedWith(NODE_VERSION_DIR_ORDER.reversed())
        .map { File(it, "bin/$executableName") }

private val NODE_VERSION_DIR_ORDER =
    Comparator<File> { a, b ->
        val x = versionKey(a.name)
        val y = versionKey(b.name)
        for (i in 0 until maxOf(x.size, y.size)) {
            val cmp = x.getOrElse(i) { 0L }.compareTo(y.getOrElse(i) { 0L })
            if (cmp != 0) return@Comparator cmp
        }
        0
    }

private fun versionKey(name: String): List<Long> = Regex("\\d+").findAll(name).mapNotNull { it.value.toLongOrNull() }.toList()
