package com.posthog.android

import com.posthog.android.PostHogGenerateMapIdTask.Companion.POSTHOG_PROGUARD_MAPPING_MAP_ID_PROPERTY
import org.gradle.api.Task
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.logging.Logger
import org.gradle.api.tasks.TaskProvider
import java.io.File
import java.security.DigestInputStream
import java.security.MessageDigest
import java.util.Locale
import java.util.Properties

internal fun ByteArray.toHex(): String {
    val result = CharArray(size * 2) { ' ' }
    var i = 0
    forEach {
        val n = it.toInt()
        result[i++] = Character.forDigit(n shr 4 and 0xF, 16)
        result[i++] = Character.forDigit(n and 0xF, 16)
    }
    return String(result)
}

/** Returns md5/sha256 hash of the file contents */
fun File.contentHash(): String {
    // first try to read hash generated by R8, which is located in the first 20 lines of mapping
    // lines are lazily iterated over, so even on huge files performance should not be a problem
    var hash: String? = null
    var index = 0
    bufferedReader().lines().use { lines ->
        for (line in lines) {
            hash = line.substringAfter("# pg_map_hash: SHA-256 ", missingDelimiterValue = "")
            if (++index > 20 || !hash.isNullOrBlank()) {
                break
            }
        }
    }
    if (!hash.isNullOrBlank()) {
        return hash!!
    }

    // otherwise fall back to calculating hash ourselves
    val md = MessageDigest.getInstance("MD5")
    DigestInputStream(inputStream(), md).buffered().readAllBytes()
    return md.digest().toHex()
}

fun String.capitalizeUS() =
    if (isEmpty()) {
        ""
    } else {
        substring(0, 1).uppercase(Locale.US) + substring(1)
    }

internal fun loadProperties(file: File): Properties {
    check(file.exists()) { "${file.name} properties file is missing" }

    return Properties().also { properties -> file.inputStream().use { properties.load(it) } }
}

fun loadPropertiesMaybe(file: File): Properties? {
    if (!file.exists()) {
        return null
    }

    return loadProperties(file)
}

fun readMapIdFromFile(file: File): String {
    val props = loadProperties(file)
    val uuid = props.getProperty(POSTHOG_PROGUARD_MAPPING_MAP_ID_PROPERTY)
    check(uuid != null) { "$POSTHOG_PROGUARD_MAPPING_MAP_ID_PROPERTY property is missing" }
    return uuid
}

fun withLogging(
    logger: Logger,
    varName: String,
    initializer: () -> TaskProvider<Task>?,
) = initializer().also { logger.info("$varName is ${it?.name}") }

fun DirectoryProperty.getAndDelete(): File {
    val file = get().asFile
    if (file.isDirectory) {
        file.deleteRecursively()
    } else {
        file.delete()
    }
    return file
}
