package com.posthog.surveys

public data class SurveyAppearance(
    val position: SurveyAppearancePosition?,
    val fontFamily: String?,
    val backgroundColor: String?,
    val submitButtonColor: String?,
    val submitButtonText: String?,
    val submitButtonTextColor: String?,
    val textColor: String?,
    val descriptionTextColor: String?,
    val ratingButtonColor: String?,
    val ratingButtonActiveColor: String?,
    val ratingButtonHoverColor: String?,
    val inputBackground: String?,
    val inputTextColor: String?,
    val whiteLabel: Boolean?,
    val autoDisappear: Boolean?,
    val displayThankYouMessage: Boolean?,
    val thankYouMessageHeader: String?,
    val thankYouMessageDescription: String?,
    val thankYouMessageDescriptionContentType: SurveyTextContentType?,
    val thankYouMessageCloseButtonText: String?,
    val borderColor: String,
    val placeholder: String?,
    val shuffleQuestions: Boolean?,
    val surveyPopupDelaySeconds: Double?,
    val widgetType: SurveyAppearanceWidgetType?,
    val widgetSelector: String?,
    val widgetLabel: String?,
    val widgetColor: String?,
    // New fields go last so existing positional copy()/componentN() usages stay compatible.
    val displayIntroScreen: Boolean? = null,
    val introScreenHeader: String? = null,
    val introScreenDescription: String? = null,
    val introScreenDescriptionContentType: SurveyTextContentType? = null,
    val introScreenButtonText: String? = null,
)
