name: Android CI

on:
  - pull_request

jobs:
  # gradle:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #   - uses: actions/checkout@v1
  #     - name: Setup JDK 1.8
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: '8'
  #         distribution: 'adopt'
  #    - name: Grant Permissions to gradlew
  #       run: chmod +x gradlew
  #     - name: Test
  #       run: ./gradlew test --tests "*"

  #   - name: Setup Gradle
  #     uses: gradle/gradle-build-action@v2

  #   - name: Execute Gradle build
  #     run: ./gradlew build

  tests:
    name: Android tests
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - name: Setup JDK 1.8
          uses: actions/setup-java@v2
          with:
            java-version: '8'
            distribution: 'adopt'
        - name: Grant Permissions to gradlew
            run: chmod +x gradlew
        - name: Test
          run: ./gradlew test --tests "*"
        # - uses: actions/checkout@v1
        #   with:
        #       fetch-depth: 1

        # - name: Set up Java 1.8
        #   uses: actions/setup-java@v1
        #   with:
        #       java-version: 1.8

        # - name: Run android tests
        #   run: /gradlew test --stacktrace
